# Generated by Django 2.0.13 on 2020-07-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ascii name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_std',
            field=models.CharField(db_index=True, max_length=200, verbose_name='standard name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ascii name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ascii name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_std',
            field=models.CharField(db_index=True, max_length=200, verbose_name='standard name'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ascii name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ascii name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_std',
            field=models.CharField(db_index=True, max_length=200, verbose_name='standard name'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ascii name'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='name_std',
            field=models.CharField(db_index=True, max_length=200, verbose_name='standard name'),
        ),
    ]
